lane :test do
	submit_jenkins_description(
      url: 'http://192.168.90.12:8080',
      job: 'DIANA-Throughput-Test-iOS',
      build: 63,
      auth: {
        username: 'nlhien',
        token: '119ed8139a4928f702d2de2663909219191'
      },
      description: "111")
end
